apiVersion: apps/v1
kind: Deployment
metadata:
  name: torch-deployment
spec:
  replicas: 1  #kubectl scale deployment torch-deployment --replicas=4   (you can use this after applying the deployment alternatively)

  selector:
    matchLabels:
      app: torch
  template:
    metadata:
      labels:
        app: torch
    spec:
      containers:
      - name: torchtest
        image: nvcr.io/nvidia/l4t-pytorch:r32.7.1-pth1.10-py3
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
